GET http://localhost:8080/api/bookstore/695944b77ed31d27662f0017 HTTP/1.1
Content-Type: application/jsonGET http://localhost:8080/api/bookstore/695944b77ed31d27662f0017 HTTP/1.1
Content-Type: application/json

###
GET http://localhost:8080/api/bookstore HTTP/1.1
Content-Type: application/json
